from datetime import datetime, time, timedelta

from odoo import api, fields, models
from odoo.exceptions import ValidationError


class MaintenanceEquipmentCategory(models.Model):
    # ke thua category cua thiet bi de cau hinh checklist/worksheet chuan theo loai thiet bi cho phase 3 buoc 4
    _inherit = "maintenance.equipment.category"

    # checklist mau de CMT doi chieu khi kiem tra ban dau
    x_psm_0502_inspection_checklist_template = fields.Text(
        string="0502 Inspection Checklist Template",
        help="Standard 0502 initial inspection checklist template for this equipment category.",
    )

    # worksheet mau de CMT co khung ghi nhan ket qua kiem tra ban dau theo loai thiet bi
    x_psm_0502_inspection_worksheet_template = fields.Text(
        string="0502 Inspection Worksheet Template",
        help="Standard 0502 initial inspection worksheet template for this equipment category.",
    )

    # template cong viec/FSM theo loai thiet bi de task buoc 9 co huong dan ky thuat sat hon
    x_psm_0502_fsm_task_template = fields.Text(
        string="0502 FSM Task Template",
        help="Standard task instruction template used when a 0502 FSM task is created for this equipment category.",
    )

    # checklist thuc thi theo loai thiet bi de ky thuat vien co khung xu ly ngay tren task
    x_psm_0502_fsm_checklist_template = fields.Text(
        string="0502 FSM Checklist Template",
        help="Standard execution checklist template used when a 0502 FSM task is created for this equipment category.",
    )

    # goi y vat tu/chuan bi theo loai thiet bi de package task ro hon
    x_psm_0502_fsm_material_template = fields.Text(
        string="0502 FSM Material Template",
        help="Standard material preparation template used when a 0502 FSM task is created for this equipment category.",
    )


class MaintenanceEquipment(models.Model):
    # ke thua model maintenance.equipment de them cau hinh lich bao tri dinh ky cho quy trinh 0502
    _inherit = "maintenance.equipment"

    # list field start

    # phong ban cua cua hang ma thiet bi nay dang thuoc ve
    # ondelete="restrict" de tranh xoa phong ban khi con thiet bi thuoc ve, tracking=True de theo doi thay doi cua truong nay tren chatter
    x_psm_0502_department_id = fields.Many2one(
        "hr.department",
        string="Store Department",
        tracking=True,
        ondelete="restrict",
        help="Store department that owns this equipment in the 0502 flow.",
    )

    # bat/tat che do sinh yeu cau bao tri dinh ky tu dong
    x_psm_0502_enable_preventive_schedule = fields.Boolean(
        string="Enable Preventive Schedule",
        tracking=True,
        help="Enable automatic preventive maintenance request generation.",
    )

    # so ngay lap lai giua hai lan bao tri dinh ky
    x_psm_0502_preventive_interval_days = fields.Integer(
        string="Preventive Interval Days",
        default=30,
        help="Number of days between preventive maintenance requests.",
    )

    # ngay den han bao tri dinh ky tiep theo
    x_psm_0502_next_preventive_date = fields.Date(
        string="Next Preventive Date",
        tracking=True,
        help="Next date when the system should generate a preventive maintenance request.",
    )

    # field luu yeu cau bao tri dinh ky gan nhat duoc sinh tu dong
    # ondelete="set null" de tranh xoa yeu cau bao tri khi record thiet bi bi xoa, readonly=True de khong cho phep nguoi dung chinh sua truc tiep tren giao dien nguoi dung
    x_psm_0502_last_preventive_request_id = fields.Many2one(
        "maintenance.request",
        string="Last Preventive Request",
        readonly=True,
        copy=False,
        ondelete="set null",
        help="Latest preventive maintenance request generated by the 0502 scheduler.",
    )
    x_psm_0502_has_open_preventive_request = fields.Boolean(
        string="Has Open Preventive Request",
        compute="_compute_x_psm_0502_preventive_status",
        store=True,
        help="Technical flag showing whether this equipment already has an open preventive request.",
    )
    x_psm_0502_preventive_status = fields.Selection(
        selection=[
            ("not_enabled", "Not Enabled"),
            ("no_next_date", "Missing Next Date"),
            ("scheduled", "Scheduled"),
            ("due", "Due to Generate"),
            ("open_request", "Open Preventive Request"),
        ],
        string="Preventive Status",
        compute="_compute_x_psm_0502_preventive_status",
        store=True,
        help="Current preventive generation status used by the 0502 scheduler.",
    )
    x_psm_0502_preventive_delay_days = fields.Integer(
        string="Preventive Delay Days",
        compute="_compute_x_psm_0502_preventive_monitoring_fields",
        store=True,
        help="Number of calendar days the preventive schedule is late or pending beyond the expected due point.",
    )
    x_psm_0502_preventive_pending_cycle_count = fields.Integer(
        string="Preventive Pending Cycles",
        compute="_compute_x_psm_0502_preventive_monitoring_fields",
        store=True,
        help="Estimated number of preventive cycles currently pending for this equipment.",
    )
    x_psm_0502_preventive_exception_status = fields.Selection(
        selection=[
            ("normal", "Normal"),
            ("missing_next_date", "Missing Next Date"),
            ("due_now", "Due Now"),
            ("multi_cycle_overdue", "Multi-cycle Overdue"),
            ("open_request_stalled", "Open Request Stalled"),
        ],
        string="Preventive Exception Status",
        compute="_compute_x_psm_0502_preventive_monitoring_fields",
        store=True,
        help="Monitoring-oriented preventive exception status for phase 3 step 5.",
    )

    # list field end

    # list method start

    # Kiem tra de dam bao khoang cach bao tri dinh ky hop le
    # rang buoc kiem tra du lieu hop le truoc khi dua vao database
    # decorator dinh nghia rang buoc du lieu o backend
    # decorator la cu phap dac biet trong python, dung de gan them hanh vi cho function

    # constraints: validate du lieu
    # neu sai: raise ValidationError de thong bao loi cho nguoi dung, va khong luu du lieu vao database
    # onchange: xu ly khi user sua UI
    # depends: dung cho compute field

    # moi khi field duoc chi dinh thay doi, thi chay ham ben duoi de kiem tra
    @api.constrains("x_psm_0502_preventive_interval_days")
    # ham duoc goi de kiem tra khi du lieu field thay doi
    # ham tu dinh nghia
    # self co the chua nhieu record, nen se loop qua tung record trong self de kiem tra
    def _check_psm_0502_preventive_interval_days(self):
        for record in self:
            if record.x_psm_0502_enable_preventive_schedule and record.x_psm_0502_preventive_interval_days < 1:
                # loi chuan cua Odoo, du lieu se khong duoc luu va hien thi loi cho user
                raise ValidationError("Preventive interval must be at least 1 day.")

    @api.depends(
        "x_psm_0502_enable_preventive_schedule",
        "x_psm_0502_next_preventive_date",
        "x_psm_0502_last_preventive_request_id",
        "x_psm_0502_last_preventive_request_id.stage_id",
        "x_psm_0502_last_preventive_request_id.archive",
        "x_psm_0502_last_preventive_request_id.maintenance_type",
        "x_psm_0502_last_preventive_request_id.x_psm_0502_request_source_code",
    )
    def _compute_x_psm_0502_preventive_status(self):
        today = fields.Date.context_today(self)
        for record in self:
            open_preventive_request = record._psm_find_open_preventive_request()
            record.x_psm_0502_has_open_preventive_request = bool(open_preventive_request)

            if not record.x_psm_0502_enable_preventive_schedule:
                record.x_psm_0502_preventive_status = "not_enabled"
            elif open_preventive_request:
                record.x_psm_0502_preventive_status = "open_request"
            elif not record.x_psm_0502_next_preventive_date:
                record.x_psm_0502_preventive_status = "no_next_date"
            elif record.x_psm_0502_next_preventive_date <= today:
                record.x_psm_0502_preventive_status = "due"
            else:
                record.x_psm_0502_preventive_status = "scheduled"

    @api.depends(
        "x_psm_0502_enable_preventive_schedule",
        "x_psm_0502_next_preventive_date",
        "x_psm_0502_preventive_interval_days",
        "x_psm_0502_last_preventive_request_id",
        "x_psm_0502_last_preventive_request_id.request_date",
        "x_psm_0502_last_preventive_request_id.stage_id",
        "x_psm_0502_last_preventive_request_id.archive",
        "x_psm_0502_last_preventive_request_id.maintenance_type",
        "x_psm_0502_last_preventive_request_id.x_psm_0502_request_source_code",
    )
    def _compute_x_psm_0502_preventive_monitoring_fields(self):
        today = fields.Date.context_today(self)
        for record in self:
            open_preventive_request = record._psm_find_open_preventive_request()
            delay_days = 0
            pending_cycles = 0
            exception_status = "normal"

            if not record.x_psm_0502_enable_preventive_schedule:
                exception_status = "normal"
            elif not record.x_psm_0502_next_preventive_date:
                exception_status = "missing_next_date"
            else:
                interval_days = record.x_psm_0502_preventive_interval_days or 0
                if record.x_psm_0502_next_preventive_date <= today:
                    delay_days = (today - record.x_psm_0502_next_preventive_date).days
                    pending_cycles = 1
                    if interval_days > 0:
                        pending_cycles = (delay_days // interval_days) + 1

                if open_preventive_request:
                    open_request_date = open_preventive_request.request_date or today
                    delay_days = max(delay_days, (today - open_request_date).days)
                    pending_cycles = max(pending_cycles, 1)
                    if interval_days > 0 and delay_days >= interval_days:
                        exception_status = "open_request_stalled"
                elif pending_cycles > 1:
                    exception_status = "multi_cycle_overdue"
                elif pending_cycles == 1:
                    exception_status = "due_now"

            record.x_psm_0502_preventive_delay_days = delay_days
            record.x_psm_0502_preventive_pending_cycle_count = pending_cycles
            record.x_psm_0502_preventive_exception_status = exception_status

    def _psm_find_open_preventive_request(self):
        self.ensure_one()
        return self.env["maintenance.request"].search([
            ("equipment_id", "=", self.id),
            ("maintenance_type", "=", "preventive"),
            ("x_psm_0502_request_source_code", "=", "preventive_schedule"),
            ("archive", "=", False),
            ("stage_id.done", "=", False),
        ], limit=1)

    def _psm_can_generate_preventive_request(self, today=None):
        self.ensure_one()
        today = today or fields.Date.context_today(self)

        if not self.x_psm_0502_enable_preventive_schedule:
            return False

        if not self.x_psm_0502_next_preventive_date:
            return False

        if self.x_psm_0502_next_preventive_date > today:
            return False

        if self._psm_find_open_preventive_request():
            return False

        return True

    # Tao bo gia tri de sinh yeu cau bao tri dinh ky tu dong
    # day la mot help function
    # day la ham phu, khong phai logic chinh, dung de chuan bi du lieu
    # ham nay khong tu tao request, ma chi chuan bi truoc du lieu
    # du lieu duoc chuan bi o day voi dang vals, va no se duoc dung de tao maintenance request moi sau nay
    # vals la mot dictionary chua du lieu de tao hoac update record
    def _psm_prepare_preventive_request_vals(self):
        # bat buoc self chi co mot record
        # neu chuyen nhieu record thi se xay ra loi
        self.ensure_one()

        # Lay nguon yeu cau va loai yeu cau da duoc dinh nghia san
        # env.ref() lay record theo xml id, day la du lieu da duoc define san trong module
        # neu khong ton tai thi tra ve None va khong bao loi
        request_source = self.env.ref(
            # module_name.record_id : ten module va id cua record trong data xml
            # xml id la ten dinh danh trong he thong cua mot record
            # record nam trong file data xml
            # khi load module, Odoo ghi record vao db va gan xml id
            # env.ref(xml_id) = lay record tu XML ID
            "M02_P0502.psm_request_source_preventive_schedule",
            # flag lam cho neu khong tim thay xml id thi tra ve None thay vi mac dinh loi
            raise_if_not_found=False,
        )
        request_type = self.env.ref(
            "M02_P0502.psm_request_type_maintenance",
            raise_if_not_found=False,
        )

        # Dat gio hen mac dinh vao 8h sang cua ngay bao tri
        # khoi tao mac dinh la khong co lich
        schedule_dt = False
        # kiem tra xem co ngay khong (bien date nay co gia tri hay khong)
        if self.x_psm_0502_next_preventive_date:
            # ham combine la ham ket hop ngay va gio thanh datetime
            # ta ghep mot ngay date voi mot time, ta se co mot bien co gia tri datetime
            # ghep ngay bao tri va thoi gian mac dinh 8h sang
            schedule_dt = datetime.combine(self.x_psm_0502_next_preventive_date, time(hour=8, minute=0))

        # Tra ve du lieu can thiet de tao maintenance request
        # phan tra du lieu vals de dung de tao mot record maintenance request moi
        # la dictionary chua tat ca field + gia tri de goi .create(vals)
        return {
            # ten cua yeu cau bao tri
            "name": f"Preventive Maintenance - {self.name}",
            # id cua thiet bi hien tai (self la record thiet bi)
            "equipment_id": self.id,
            # loai bao tri dinh ky
            "maintenance_type": "preventive",
            # nguoi phu trach sua chua - technician (neu co id thi lay id, neu khong thi tra ve False)
            "user_id": self.technician_user_id.id or False,
            # uu tien ngay bao tri tiep theo, neu khong co thi lay ngay hien tai
            # fields.Date.context_today(self) = lay ngay hien tai theo timezone cua user
            "request_date": self.x_psm_0502_next_preventive_date or fields.Date.context_today(self),
            # gia tri datetime da duoc chuan bi
            "schedule_date": schedule_dt,
            # neu co request source thi lay id, neu khong thi tra ve False
            "x_psm_0502_request_source_id": request_source.id if request_source else False,
            # danh dau nguon he thong ky thuat cua request preventive do cron sinh ra
            "x_psm_0502_source_system": "preventive_cron",
            # luu reference de doi chieu nhanh ve thiet bi phat sinh yeu cau
            "x_psm_0502_source_reference": self.display_name,
            # id cua phong ban cua thiet bi, neu co thi lay id, neu khong thi tra ve False
            "x_psm_0502_department_id": self.x_psm_0502_department_id.id or False,
            # id cua loai request
            "x_psm_0502_request_type_id": request_type.id if request_type else False,
            # mo ta dang html va hien thi trong chatter cua maintenance request, giai thich nguon goc cua yeu cau bao tri nay
            "description": (
                "<p>This request was generated automatically from the equipment preventive maintenance schedule.</p>"
            ),
        }

    # Tinh ngay bao tri tiep theo dua tren ngay co so va so ngay lap lai
    # ham tinh ngay bao tri ke tiep
    def _psm_compute_next_preventive_date(self, base_date):
        # dam bao chi su ly mot record
        self.ensure_one()
        # neu chua set gia tri, thi mac dinh cua so ngay lap lai giua hai lan bao tri dinh ky la 0
        interval_days = self.x_psm_0502_preventive_interval_days or 0
        # base_date la ngay co so de tinh, neu khong co thi tra ve ngay do luon
        if not base_date or interval_days < 1:
            return base_date

        # Tiep tuc cong don den khi ngay tiep theo nam sau hom nay
        # bat dau tu ngay goc
        next_date = base_date
        # today la lay ngay hien tai theo timezone cua user
        today = fields.Date.context_today(self)
        # cong don chu ky cho den khi ngay vuot qua hom nay
        while next_date <= today:
            next_date += timedelta(days=interval_days)
        return next_date

    # Cron tu dong tao yeu cau bao tri khi toi han
    # ham cron tu dong sinh yeu cau bao tri
    # decorator @api.model, dinh nghia ham nay la method cua model, khong phu thuoc vao record nao, va duoc goi truc tiep tu model
    # ham la scheduled action goi tu dong
    @api.model
    def cron_psm_generate_preventive_requests(self):
        # Lay ngay hien tai de tim cac thiet bi da den han
        # dung ngay hom nay de tim nhung thiet bi da toi han bao tri
        today = fields.Date.context_today(self)
        # tim cac thiet bi thoa 3 dieu kien
        # thiet bi co bat lich bao tri dinh ky
        # thiet bi co ngay bao tri tiep theo
        # ngay bao tri tiep theo khong duoc qua hom nay
        equipments = self.search([
            ("x_psm_0502_enable_preventive_schedule", "=", True),
            ("x_psm_0502_next_preventive_date", "!=", False),
            ("x_psm_0502_next_preventive_date", "<=", today),
        ])

        # Duyet tung thiet bi va tranh tao trung yeu cau cung loai
        request_model = self.env["maintenance.request"]
        for equipment in equipments:
            existing_request = equipment._psm_find_open_preventive_request()

            # neu co mot yeu cau bao tri con chua hoan thanh
            if existing_request:
                equipment.x_psm_0502_last_preventive_request_id = existing_request.id
                # dam bao request preventive dang mo van co dau vet notify lead trong phase 1
                # kiem tra da gui thong bao cho CMT Lead chua, neu chua thi gui thong bao
                # neu khong co dong if nay thi se tro thanh spam cho lead vi moi lan cron chay thi deu gui thong bao cho lead
                # vay nen chi notify 1 lan duy nhat cho moi request preventive
                if not existing_request.x_psm_0502_lead_notified_at:
                    # goi ham action_psm_notify_lead de gui thong bao cho CMT Lead
                    existing_request.action_psm_notify_lead()
                continue

            if not equipment._psm_can_generate_preventive_request(today=today):
                continue

            # Neu chua co thi tao moi yeu cau bao tri dinh ky
            new_request = request_model.create(equipment._psm_prepare_preventive_request_vals())
            # tao activity thong bao cho CMT Lead ngay khi request preventive vua duoc sinh ra
            # sau khi tao request moi, thi goi ham action_psm_notify_lead de gui thong bao cho CMT Lead
            new_request.action_psm_notify_lead()
            # tao xong thi cap nhat lai thiet bi voi id cua request vua tao, tinh ngay bao tri tiep theo dua tren ngay goc cua thiet bi
            equipment.write({
                "x_psm_0502_last_preventive_request_id": new_request.id,
                "x_psm_0502_next_preventive_date": equipment._psm_compute_next_preventive_date(
                    equipment.x_psm_0502_next_preventive_date
                ),
            })

    # list method end
